### Asynchronous call the GetPlanetResidentsOrchestrator Function
POST http://localhost:7071/api/start/GetPlanetResidentsOrchestrator
Content-Type: application/json

"tat"


### Synchronous call the GetPlanetResidentsOrchestrator Function
POST http://localhost:7071/api/startandwait/GetPlanetResidentsOrchestrator
    ?timeout=15
    &interval=2
Content-Type: application/json

"tat"


### Check the status of the orchestrator function.
### Update the orchestratorInstanceId and storageCode 
### so it matches the ID of your running orchestrator instance.
@orchestratorInstanceId = 5b4be602aee04d44b041b85edf692243
@storageCode = Fc0DqzcoZ3QyN2gazAqWMEJDLYXeTJJIR8mmn/Fa8pW40Xq3Ual/eg==
@hubName=GlobalAzureBootcamp
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{orchestratorInstanceId}}
    ?taskHub={{hubName}}
    &connection=Storage
    &code={{storageCode}}


####



    serverlesstoronto.org

    daniel.zivkovic@gmail.Content-MD5: 
    